version: '3.8'

services:
  auth:
    image: auth-auth:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./auth/.env
    ports:
      - "3001:3001"
    volumes:
      - "./mock_data:/app/mock_data"
  
  frontend:
    image: frontend-frontend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - "./mock_data:/app/mock_data"

  get-all-meter-usage:
    image: get-all-meter-usage-get-all-meter-usage:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-getter/get-all-meter-usage/.env
    ports:
      - "8006:8006"
    volumes:
      - "./mock_data:/app/mock_data"

  get-hub-meter-usage:
    image: get-hub-meter-usage-get-hub-meter-usgae:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-getter/get-hub-meter-usage/.env    
    ports:
      - "8003:8003"
    volumes:
      - "./mock_data:/app/mock_data"

  get-meter-usage:
    image: get-meter-usage-get-meter-usage:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any   
    ports:
      - "8002:8002"
    volumes:
      - "./mock_data:/app/mock_data"

  get-online-hub:
    image: get-online-hub-get-online-hub:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-getter/get-online-hub/.env
    ports:
      - "8005:8005"
    volumes:
      - "./mock_data:/app/mock_data"
      
  get-online-meter:
    image: get-online-meter-get-online-meter:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-getter/get-online-meter/.env
    ports:
      - "8004:8004"
    volumes:
      - "./mock_data:/app/mock_data"

  create-meter-service:
    image: create-meter-service-create-meter-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-manager/create-meter-service/.env
    ports:
      - "3006:3006"
    volumes:
      - "./mock_data:/app/mock_data"

  delete-meter-service:
    image: delete-meter-service-delete-meter-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-manager/delete-meter-service/.env
    ports:
      - "3007:3007"
    volumes:
      - "./mock_data:/app/mock_data"

  get-meter-service:
    image: get-meter-service-get-meter-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-manager/get-meter-service/.env
    ports:
      - "3008:3008"
    volumes:
      - "./mock_data:/app/mock_data"                    

  update-meter-service:
    image: update-meter-service-update-meter-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-manager/update-meter-service/.env
    ports:
      - "3009:3009"
    volumes:
      - "./mock_data:/app/mock_data"                    

  create-config:
    image: create-config-create-config:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any  
    env_file:
      - ./meter-setter/create-config/.env
    ports:
      - "3013:3013"
    volumes:
      - "./mock_data:/app/mock_data"                    

  delete-config:
    image: delete-config-delete-config:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-setter/delete-config/.env
    ports:
      - "3014:3014"
    volumes:
      - "./mock_data:/app/mock_data"

  get-config:
    image: get-config-get-config:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-setter/get-config/.env
    ports:
      - "3015:3015"
    volumes:
      - "./mock_data:/app/mock_data"

  update-config:
    image: update-config-update-config:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./meter-setter/update-config/.env
    ports:
      - "3016:3016"
    volumes:
      - "./mock_data:/app/mock_data"

  create-hub-service:
    image: create-hub-service-create-hub-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./smh-manager/create-hub-service/.env
    ports:
      - "3002:3002"
    volumes:
      - "./mock_data:/app/mock_data"

  delete-hub-service:
    image: delete-hub-service-delete-hub-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./smh-manager/delete-hub-service/.env
    ports:
      - "3003:3003"
    volumes:
      - "./mock_data:/app/mock_data"    

  get-hub-service:
    image: get-hub-service-get-hub-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./smh-manager/get-hub-service/.env
    ports:
      - "3004:3004"
    volumes:
      - "./mock_data:/app/mock_data"    

  update-hub-service:
    image: update-hub-service-update-hub-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./smh-manager/update-hub-service/.env
    ports:
      - "3005:3005"
    volumes:
      - "./mock_data:/app/mock_data"    
             
  set-all-meters-by-hub-id-service:
    image: set-all-meters-by-hub-id-service-set-all-meters-by-hub-id-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./user-management/set-all-meters-by-hub-id-service/.env
    ports:
      - "3011:3011"
    volumes:
      - "./mock_data:/app/mock_data"                                  

  set-hub-status-service:
    image: set-hub-status-service-set-hub-status-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./user-management/set-hub-status-service/.env
    ports:
      - "3012:3012"
    volumes:
      - "./mock_data:/app/mock_data"                                  

  set-meter-by-id-service:
    image: set-meter-by-id-service-set-meter-by-id-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./user-management/set-meter-by-id-service/.env
    ports:
      - "3010:3010"
    volumes:
      - "./mock_data:/app/mock_data"                                  
      