packages:
  - 'frontend'
  - 'auth'
  - 'smh-manager'
  - 'meter-manager/create-meter-service'
  - 'meter-manager/delete-meter-service'
  - 'meter-manager/get-meter-service'
  - 'meter-manager/update-meter-service'
  - 'smh-manager/create-hub-service'
  - 'smh-manager/delete-hub-service'
  - 'smh-manager/get-hub-service'
  - 'smh-manager/update-hub-service'
  - 'meter-setter/set-all-meters-by-hub-id-service'
  - 'meter-setter/set-meter-by-id-service'
