name: Test CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        #node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          git clone https://github.com/TetraHikari/halfhourly_reduced
          mv halfhourly_reduced/halfhourly_dataset ./mock_data/
          rm -rf meter-dataset
          npm install -g pnpm
          rm pnpm-lock.yaml
          pnpm install

      - name: Start services
        run: |
          pnpm run dev &
          python3 run_services.py &
          sleep 30
          ps aux | grep 'pnpm\|python3'

      - name: Brute force 3001/login
        run: |
          curl -X POST http://localhost:3001/login -H "Content-Type: application/json" -d '{"email": "admin@gmail.com", "password": "admin"}'


      #- name: Check protected port
      #  run : |
      # TBD

      - name: Stub generation
        run: |
          echo "Generating stub data..."
          pip install faker
          python -c "
          import json
          import random
          from faker import Faker

          fake = Faker()
          data = []
          for _ in range(100):
              data.append({
                  'email': fake.email(),
                  'password': fake.password(),
              })

          with open('testing/stub_data.json', 'w') as f:
              json.dump(data, f)
          "
          echo "Stub data generated"

      - name: Stress test
        run: |
          echo "Stress testing..."
          curl -X POST http://localhost:3001/register -H "Content-Type: application/json" -d @testing/stub_data.json
          echo "Stress test done"


      - name: Check ports and terminate services
        run: |
          check_ports() {
            for port in "$@"; do
              if ! nc -z localhost "$port"; then
                echo "Port $port is not alive"
                exit 1
              fi
            done
          }

          check_ports 3000 8002 8003 8004 8005 8006
          
          pkill -f "pnpm run dev"
          pkill -f "python3 run_services.py"

      - name: CI deploy
        run: echo "This is a mock deploy step"
