name: Test CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        #node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          git clone https://github.com/TetraHikari/halfhourly_reduced
          mv halfhourly_reduced/halfhourly_dataset ./mock_data/
          rm -rf meter-dataset
          npm install -g pnpm
          pnpm install

      - name: Start services
        run: |
          pnpm run dev &
          python3 run_services.py &
          sleep 20

      - name: Check ports and terminate services
        run: |
          check_ports() {
            for port in "$@"; do
              if ! nc -z localhost "$port"; then
                echo "Port $port is not alive"
                exit 1
              fi
            done
          }

          check_ports 3000 8000 8001 8002 8003
          
          pkill -f "pnpm run dev"
          pkill -f "python3 run_services.py"

      - name: Always pass
        run: echo "PASS"
